config/routes.rb
Rails.application.routes.draw do

  namespace :incoming do
    post 'slack', to: 'slack#index'
  end

  namespace :admin do
    resources :users

    resources :articles
    resources :manufacturers
    resources :merchants
    resources :orders
    resources :order_state_logs
    resources :product_families
    resources :products
    resources :streaming_sites
    resources :terms
    resources :videos

    root to: "users#index"
  end

  get 'about/index', as: :about

  namespace :dji_track do
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        get 'edit', as: :edit
        post 'cancel', as: :cancel

        get 'chart_data', as: :chart_data
        get 'country_chart_data', as: :country_chart_data
        get 'recently_shipped_chart_data', as: :recently_shipped_chart_data
        get 'order_month_chart_data', as: :order_month_chart_data

        get 'recent', as: :recent
        get 'charts', as: :charts
      end
      member do
        get 'history', as: :history
      end
    end
    root to: 'visitors#index'
  end

  resources :manufacturers
  constraints(host: /dji-track.herokuapp.com/) do
    match "/(*path)" => redirect { |params, req| "//www.dronehome.io/#{params[:path]}" },  via: [:get, :post]
  end
  
  resources :merchants

  namespace :news do
    resources :articles
    root to: 'articles#index'
  end

  resources :order_state_logs

  resources :products

  resources :streaming_sites, except: [:edit, :update, :destroy]

  resources :terms
  get 'terminology', to: 'terminology#index', as: :terminology

  devise_for :users
  resources :users

  resources :videos, except: [:edit, :update, :destroy]

  get '/orders', to: redirect('/dji_track/orders')
  get '/orders/new', to: redirect('/dji_track/orders/new')

  # Errors
  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  root to: 'visitors#index'
end

app/controllers/dji_track/visitors_controller.rb
class DjiTrack::VisitorsController < ApplicationController
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/views/visitors/index.html.haml
.jumbotron.text-xs-center
  = image_tag 'quadbot-happy.png', width: 325
  %small.text-muted
    Meet Quadbot.
  %h1.display-5 Welcome to DroneHome!
  %p.lead
    A home for drone enthusiasts to learn about the newest drones, drone news, drone laws, and connect with other drone pilots.

.row
  .col-md-4
    .card
      .card-block
        %h4.card-title Drone News
        %p.card-text
          Learn about the latest happenings in the world of drones, from new outlandish laws about where you can fly,
          to the latest news about new drone products. Easy way for you to know what is going
          on in the community.
        .text-xs-center
          = link_to 'Read News', news_root_path, class: 'btn btn-info'
      .card-footer
        .text-muted
          Submit an article!
  .col-md-4
    .card
      .card-block
        %h4.card-title Order Tracking
        %p.card-text
          Track orders of DJI products from a variety of merchants, such as DJI, Amazon, and Best Buy. This is especially helpful during preorder
          and recent launches due to the general silence from DJI about shipping status.
        .text-xs-center
          = link_to 'Track Orders', dji_track_root_path, class: 'btn btn-primary'
      .card-footer
        .text-muted
          And contribute your order data!
  .col-md-4
    .card
      .card-block
        %h4.card-title Drone Chat
        %p.card-text
          Realtime discussions with other drone enthusiasts. DroneHome on Slack has many rooms to discuss specific drone brands and models, as well as regional rooms to talk to drone
          pilots in your neck of the woods.
        .text-xs-center
          = link_to 'Request Invitation', 'https://welike.typeform.com/to/m03t7Q', class: 'btn btn-warning'
      .card-footer
        .text-muted
          It's free and public.

.jumbotron.text-xs-center
  %h2
    Want a sticker or two?
  = mail_to 'hello@dronehome.io', 'Say Hello', subject: 'Stickers', class: 'btn btn-lg btn-primary'