config/routes.rb
Rails.application.routes.draw do

  namespace :incoming do
    post 'slack', to: 'slack#index'
  end

  namespace :admin do
    resources :users

    resources :articles
    resources :manufacturers
    resources :merchants
    resources :orders
    resources :order_state_logs
    resources :product_families
    resources :products
    resources :streaming_sites
    resources :terms
    resources :videos

    root to: "users#index"
  end

  get 'about/index', as: :about

  namespace :dji_track do
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        get 'edit', as: :edit
        post 'cancel', as: :cancel

        get 'chart_data', as: :chart_data
        get 'country_chart_data', as: :country_chart_data
        get 'recently_shipped_chart_data', as: :recently_shipped_chart_data
        get 'order_month_chart_data', as: :order_month_chart_data

        get 'recent', as: :recent
        get 'charts', as: :charts
      end
      member do
        get 'history', as: :history
      end
    end
    root to: 'visitors#index'
  end

  resources :manufacturers
  constraints(host: /dji-track.herokuapp.com/) do
    match "/(*path)" => redirect { |params, req| "//www.dronehome.io/#{params[:path]}" },  via: [:get, :post]
  end
  
  resources :merchants

  namespace :news do
    resources :articles
    root to: 'articles#index'
  end

  resources :order_state_logs

  resources :products

  resources :streaming_sites, except: [:edit, :update, :destroy]

  resources :terms
  get 'terminology', to: 'terminology#index', as: :terminology

  devise_for :users
  resources :users

  resources :videos, except: [:edit, :update, :destroy]

  get '/orders', to: redirect('/dji_track/orders')
  get '/orders/new', to: redirect('/dji_track/orders/new')

  # Errors
  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  root to: 'visitors#index'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :streaming_site
  belongs_to :user, required: false

  acts_as_taggable

  scope :published, -> { where(status: 'published') }

  validates :summary, presence: true
  validates :url, presence: true, uniqueness: true

  before_save :update_from_source

  def publish!
    update(status: 'published', published_at: Time.current)
  end

  def update_from_source
    if url.present?
      begin
        video_info = VideoInfo.new(url)
 
        if video_info.available?
          self.title        = video_info.title
          self.description  = video_info.description
          self.channel_name = video_info.author
          self.channel_url  = video_info.author_url
          self.thumbnail_url_small   = video_info.thumbnail_small
          self.thumbnail_url_medium  = video_info.thumbnail_medium
          self.thumbnail_url_large   = video_info.thumbnail_large
          self.embed_url             = video_info.embed_url
          self.embed_code            = video_info.embed_code
          self.provider_published_at = video_info.date
          self.duration              = video_info.duration
        end
      rescue VideoInfo::UrlError => e
        puts "Error retrieving #{url}: #{e.to_s}"
      end
    end
  end
end

app/controllers/admin/videos_controller.rb
module Admin
  class VideosController < Admin::ApplicationController

  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show]

  def index
    @videos = Video.published.order(published_at: :desc)
  end

  def show
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path, notice: 'Your video submission was received and will be reviewed before publishing. Thank you!' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:streaming_site_id, :title, :summary, :description, :url, :channel_name, :channel_url, :user_id, :status)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :url, 'URL'
    = f.text_field :url, class: 'form-control', placeholder: 'http://www.youtube.com/watch?asjdkajk'
    %small.text-muted
      A link to the YouTube or Vimeo video on the source site.
  .form-group
    = f.label :summary
    = f.text_area :summary, class: 'form-control', placeholder: 'A short clip of a guy flying his new DJI Mavic and then stupidly flies it directly into a wall. User error!'
    %small.text-muted
      Your own summary of what the video is about, but do not copy &amp; paste the title. We will retrieve the real title and description automatically.

  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/videos/index.html.haml
%h1
  Videos
  .float-xs-right
    = link_to 'Submit a Video', new_video_path, class: 'btn btn-primary'
%p.text-muted
  Great videos about specific drones that
  have found online, as well as your own videos that share experiences, tips, or
  completed projects to be shown off.

%br

.videos
  - @videos.each do |video|
    .video
      .video-body.embed-responsive.embed-responsive-16by9
        - if video.embed_code.present?
          = video.embed_code.html_safe
      .video-header
        .row
          .col-xs-9
            %h4.video-title
              = link_to video.title, video.url, target: '_blank'
            %h6.video-posted-at.text-muted
              = video.published_at.to_s(:long)
          .col-xs-3.text-xs-right
            - if video.user.present? && video.user.gravatar_url.present?
              = image_tag video.user.gravatar_url, height: 25, class: 'rounded-circle'
              #{video.user.username}
            - else
              Anonymous  

      .video-description
        .video-summary
          = video.summary
      .video-footer
        .video-tags
          - video.tags.each do |tag|
            .tag.tag-default
              = tag.name
%br

app/views/videos/new.html.haml
%h1 New Video
%p.text-muted
  Submit your videos for inclusion on DroneHome's Videos section. These videos should be
  informative, helpful, or otherwise beautiful to watch. You are allowed to submit your
  own footage and projects, but know that we will review submissions.
  
= render 'form'

app/views/videos/show.html.haml
%p#notice= notice

%p
  %b Streaming site:
  = @video.streaming_site
%p
  %b Title:
  = @video.title
%p
  %b Summary:
  = @video.summary
%p
  %b Description:
  = @video.description
%p
  %b Url:
  = @video.url
%p
  %b Channel name:
  = @video.channel_name
%p
  %b Channel url:
  = @video.channel_url
%p
  %b User:
  = @video.user
%p
  %b Status:
  = @video.status

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path