config/routes.rb
Rails.application.routes.draw do

  namespace :incoming do
    post 'slack', to: 'slack#index'
  end

  namespace :admin do
    resources :users

    resources :articles
    resources :manufacturers
    resources :merchants
    resources :orders
    resources :order_state_logs
    resources :product_families
    resources :products
    resources :streaming_sites
    resources :terms
    resources :videos

    root to: "users#index"
  end

  get 'about/index', as: :about

  namespace :dji_track do
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        get 'edit', as: :edit
        post 'cancel', as: :cancel

        get 'chart_data', as: :chart_data
        get 'country_chart_data', as: :country_chart_data
        get 'recently_shipped_chart_data', as: :recently_shipped_chart_data
        get 'order_month_chart_data', as: :order_month_chart_data

        get 'recent', as: :recent
        get 'charts', as: :charts
      end
      member do
        get 'history', as: :history
      end
    end
    root to: 'visitors#index'
  end

  resources :manufacturers
  constraints(host: /dji-track.herokuapp.com/) do
    match "/(*path)" => redirect { |params, req| "//www.dronehome.io/#{params[:path]}" },  via: [:get, :post]
  end
  
  resources :merchants

  namespace :news do
    resources :articles
    root to: 'articles#index'
  end

  resources :order_state_logs

  resources :products

  resources :streaming_sites, except: [:edit, :update, :destroy]

  resources :terms
  get 'terminology', to: 'terminology#index', as: :terminology

  devise_for :users
  resources :users

  resources :videos, except: [:edit, :update, :destroy]

  get '/orders', to: redirect('/dji_track/orders')
  get '/orders/new', to: redirect('/dji_track/orders/new')

  # Errors
  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  root to: 'visitors#index'
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  has_many :orders

  scope :active, -> { where(status: 'active') }
end

app/controllers/admin/merchants_controller.rb
module Admin
  class MerchantsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Merchant.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Merchant.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name, :description, :website, :referral_code, :status)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.haml
= form_for @merchant do |f|
  - if @merchant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@merchant.errors.count, "error")} prohibited this merchant from being saved:"
      %ul
        - @merchant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :referral_code
    = f.text_field :referral_code
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/merchants/edit.html.haml
%h1 Editing merchant

= render 'form'

= link_to 'Show', @merchant
\|
= link_to 'Back', merchants_path

app/views/merchants/index.html.haml
%h1 Listing merchants

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Website
      %th Referral code
      %th Status
      %th
      %th
      %th

  %tbody
    - @merchants.each do |merchant|
      %tr
        %td= merchant.name
        %td= merchant.description
        %td= merchant.website
        %td= merchant.referral_code
        %td= merchant.status
        %td= link_to 'Show', merchant
        %td= link_to 'Edit', edit_merchant_path(merchant)
        %td= link_to 'Destroy', merchant, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Merchant', new_merchant_path

app/views/merchants/new.html.haml
%h1 New merchant

= render 'form'

= link_to 'Back', merchants_path

app/views/merchants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @merchant.name
%p
  %b Description:
  = @merchant.description
%p
  %b Website:
  = @merchant.website
%p
  %b Referral code:
  = @merchant.referral_code
%p
  %b Status:
  = @merchant.status

= link_to 'Edit', edit_merchant_path(@merchant)
\|
= link_to 'Back', merchants_path