config/routes.rb
Rails.application.routes.draw do

  namespace :incoming do
    post 'slack', to: 'slack#index'
  end

  namespace :admin do
    resources :users

    resources :articles
    resources :manufacturers
    resources :merchants
    resources :orders
    resources :order_state_logs
    resources :product_families
    resources :products
    resources :streaming_sites
    resources :terms
    resources :videos

    root to: "users#index"
  end

  get 'about/index', as: :about

  namespace :dji_track do
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        get 'edit', as: :edit
        post 'cancel', as: :cancel

        get 'chart_data', as: :chart_data
        get 'country_chart_data', as: :country_chart_data
        get 'recently_shipped_chart_data', as: :recently_shipped_chart_data
        get 'order_month_chart_data', as: :order_month_chart_data

        get 'recent', as: :recent
        get 'charts', as: :charts
      end
      member do
        get 'history', as: :history
      end
    end
    root to: 'visitors#index'
  end

  resources :manufacturers
  constraints(host: /dji-track.herokuapp.com/) do
    match "/(*path)" => redirect { |params, req| "//www.dronehome.io/#{params[:path]}" },  via: [:get, :post]
  end
  
  resources :merchants

  namespace :news do
    resources :articles
    root to: 'articles#index'
  end

  resources :order_state_logs

  resources :products

  resources :streaming_sites, except: [:edit, :update, :destroy]

  resources :terms
  get 'terminology', to: 'terminology#index', as: :terminology

  devise_for :users
  resources :users

  resources :videos, except: [:edit, :update, :destroy]

  get '/orders', to: redirect('/dji_track/orders')
  get '/orders/new', to: redirect('/dji_track/orders/new')

  # Errors
  match '/404', to: 'errors#not_found', via: :all, as: :error_404
  match '/500', to: 'errors#internal_server_error', via: :all, as: :error_500

  root to: 'visitors#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :product_family

  acts_as_taggable_on :features

  scope :accessories, -> { where(accessory: true) }
  scope :non_accessories, -> { where(accessory: false) }
  scope :published, -> { where(status: 'published') }

  def amazon_affiliate_code
    "dronehome00-20"
  end

  def amazon_url
    id = asin.presence || upc.presence
    "http://www.amazon.com/dp/#{id}/?tag=#{amazon_affiliate_code}"
  end

  def manufacturer_product_name
    "#{manufacturer.name} #{name}"
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @manufacturers  = Manufacturer.includes(:product_families, :products).order(common_name: :asc)
    @product_family = ProductFamily.where(id: params[:product_family].to_i).includes(:manufacturer, :products).first
    @products, @accessories = if @product_family.present?
      [@product_family.products.non_accessories.order(name: :asc), @product_family.products.accessories.order(name: :asc)]
    else
      [Product.non_accessories.order(name: :asc), Product.accessories.order(name: :asc)]
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:manufacturer_id, :product_family_id, :name, :code, :accessory, :description, :logo_url, :website, :upc, :asin, :dji_store_url, :status)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :manufacturer_id, 'Manufacturer'
    = f.collection_select :manufacturer_id, Manufacturer.order(name: :asc), :id, :name, prompt: 'Select a Manufacturer'
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :logo_url
    = f.text_field :logo_url
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :upc
    = f.text_field :upc
  .field
    = f.label :asin
    = f.text_field :asin
  .field
    = f.label :dji_store_url
    = f.text_field :dji_store_url
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/products/_product.html.haml
.card.product
  .card-img-top.product-image.text-xs-center
    = image_tag product.logo_url, class: 'img-fluid'
  .card-block
    %h5.card-title
      = product.name
    %h6.card-subtitle.text-muted
      = product.manufacturer.name
  .card-block
    %p.card-text
      = product.description
  .card-footer
    - if product.website.present?
      = link_to 'More Info', product.website, class: 'btn btn-sm btn-outline-secondary', target: '_blank'
    .float-xs-right
      - if product.dji_store_url.present?
        = link_to 'DJI Store', product.dji_store_url, class: 'btn btn-sm btn-outline-info', target: '_blank'
      - if product.asin.present? || product.upc.present?
        = link_to 'Amazon', product.amazon_url, class: 'btn btn-sm btn-outline-success'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
.jumbotron
  %h1.display-4 Products
  %p.lead
    Learn about available drones and their accessories for a variety of market leading drone manufacturers.
  %p.text-muted
    If you are planning to purchase a drone in the near future, make sure that you consider buying through a link
    below in order to benefit our community. All purchases made by clicking links from here result in helping
    to offset the cost of running this community and will ensure that it continues to grow.
    Tell your friends.

.row
  .col-sm-4

    .product-menu-section
      %h4.text-muted
        All Manufacturers
      %ul.list-group
        = link_to 'All Products', products_path, class: (params[:product_family].to_i == 0 ? 'list-group-item list-group-item-action active' : 'list-group-item list-group-item-action')

    - @manufacturers.each do |manufacturer|
      .product-menu-section
        %h4.text-muted
          = manufacturer.common_name

        %ul.list-group
          - manufacturer.product_families.active.each do |product_family|
            = link_to product_family.name, products_path(request.query_parameters.merge(product_family: product_family.id)), class: (params[:product_family].to_i == product_family.id ? 'list-group-item list-group-item-action active' : 'list-group-item list-group-item-action')

  .col-sm-8
    .product-group
      %h4.text-muted
        - if @product_family.present?
          = @product_family.name
        - else
          All Products

      - if @products.count > 0
        - @products.each do |product|
          .card-deck-wrapper
            .card-deck
              = render product
      - else
        No products yet.

    .product-group
      %h4.text-muted
        - if @product_family.present?
          = @product_family.name
          Accessories
        - else
          All Accessories

      - if @accessories.count > 0
        - @accessories.each do |product|
          .card-deck-wrapper
            .card-deck
              = render product
      - else
        No accessories for this product family yet.

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Manufacturer:
  = @product.manufacturer
%p
  %b Name:
  = @product.name
%p
  %b Code:
  = @product.code
%p
  %b Description:
  = @product.description
%p
  %b Logo url:
  = @product.logo_url
%p
  %b Website:
  = @product.website
%p
  %b Upc:
  = @product.upc
%p
  %b Asin:
  = @product.asin
%p
  %b Status:
  = @product.status

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path